spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  flyway:
    enabled: true
    create-schemas: true
    schemas: gdsc-migration
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: root
